backend:
  name: github
  repo: clement83/site
  branch: main
  auth_type: implicit
  base_url: https://github.com/login/oauth/authorize
  client_id: Ov23li2q5RFwDfbcHB5t

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Corps", name: "body", widget: "markdown"}
